# Generated by Django 3.0.3 on 2020-02-14 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200214_1200'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blogs',
        ),
    ]
